"""Protocol 仅定义协作签名，不包含业务实现。"""
from collections.abc import Iterator
from typing import Protocol
from minisql.contracts.models import (
    CacheStats, ExecutionResult, RecordId, ReplacementEvent, Row,
    StoredRecord, TableSchema,
)
from minisql.contracts.plans import CompilationResult, Plan


class CatalogReader(Protocol):
    def get_table(self, name: str) -> TableSchema | None: ...
    def list_tables(self) -> tuple[TableSchema, ...]: ...


class CatalogWriter(CatalogReader, Protocol):
    def bootstrap(self) -> None: ...
    def register_table(self, schema: TableSchema) -> None: ...


class Compiler(Protocol):
    def compile(self, sql: str, catalog: CatalogReader) -> CompilationResult: ...
    def split_statements(self, sql: str) -> tuple[str, ...]: ...


class RecordStorage(Protocol):
    def create_table(self, schema: TableSchema) -> TableSchema: ...
    def insert(self, schema: TableSchema, row: Row) -> RecordId: ...
    def scan(self, schema: TableSchema) -> Iterator[StoredRecord]: ...
    def delete(self, schema: TableSchema, record_id: RecordId) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...


class PageManager(Protocol):
    def allocate_page(self) -> int: ...
    def free_page(self, page_id: int) -> None: ...
    def read_page(self, page_id: int) -> bytes: ...
    def write_page(self, page_id: int, data: bytes) -> None: ...
    def close(self) -> None: ...


class BufferPool(Protocol):
    def get_page(self, page_id: int) -> bytearray: ...
    def mark_dirty(self, page_id: int) -> None: ...
    def flush_page(self, page_id: int) -> None: ...
    def flush_all(self) -> None: ...
    def stats(self) -> CacheStats: ...
    def replacement_log(self) -> tuple[ReplacementEvent, ...]: ...


class Executor(Protocol):
    def execute(self, plan: Plan) -> ExecutionResult: ...
